---
title: "Plotting scripts"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
library(nlme)
library(lmerTest)
library(knitr)
library(emmeans)
library(ggpubr)
library(plotrix)
library(varTestnlme)
library(reshape2)
library(ggrepel)
library(viridis)
library(cowplot)
```

*Loading and combining datasets*

```{r}
#total scent dataset
scent <- read_csv("scents_honest.csv") %>% mutate(ID=as.character(ID)) 

#compound scent dataset
scent_comps <- read_csv("compounds_honest.csv") %>% mutate(ID=as.character(ID))

#converting compound scent dataset (with peak areas) into emission rates
funfun <- function(col, tol.area, N.fl){
  (col/tol.area)*23.6*55*(1/3)*(1/N.fl)
}

scent_comps_calc <- scent_comps %>% mutate_at(c(4:12), ~replace(., is.na(.), 0)) %>% left_join(., scent, by="ID")
scent_comps_calc <-scent_comps_calc  %>% mutate_at(c(4:12), list(~funfun(., Toluene_adj.y,NFlowers.x)))

#nectar on the plant level
nectar_plant <- read_csv("nectar_for_scent_HT_short.csv") %>% mutate(Plant_id=as.factor(as.character(Plant_id)))

#nectar on the flower level
nectar_flower <- read_csv("nectar_protocol.csv") %>% mutate(Population=as.factor(Population), Plant_ID=as.factor(as.character(Plant_ID)), Flower_id=as.factor(as.character(Flower_id)), plant_id=as.factor(as.character(plant_id)))


nectar_size_plant <- nectar_flower %>% filter(Corola_area_mm2!="NA") %>%   group_by(Population, plant_id) %>% summarize(size=mean(Corola_area_mm2), nect=mean(nectar_μl))

nectar_size_plant <- left_join(nectar_size_plant, nectar_plant,   by=c("Population", "plant_id"="Plant_id")) %>% group_by(Population) %>%  filter(length(unique(plant_id))>=8) %>% dplyr::select(-Mean_nectar, -Notes, -`X7`)

nectar_size_scent <- left_join(nectar_size_plant, scent, by=c("Scent_ID"="ID")) %>%  filter(Scent_ID!="NA") %>% drop_na() %>% mutate(log_size = log(size), log_nect=log(nect+0.0001), log_scent=log(total_tol))


scent_nectar <- left_join(nectar_plant, scent, by=c("Scent_ID" = "ID"))

comps_nectar <- left_join(nectar_plant, scent_comps_calc, by=c("Scent_ID" = "ID"))

```

```{r}

nectar_flower_pop <- nectar_flower %>% group_by(Population) %>% filter(length(unique(Plant_ID))>=8)

nectar_flower_work <- nectar_flower %>% filter(!is.na(Population)) %>%  filter(!is.na(nectar_μl)) %>% filter(!is.na(Corola_area_mm2)) %>% filter(Corola_area_mm2>0) %>% filter(Population %in% nectar_flower_pop$Population)

nectar_flower_work$Mating_system <- if_else(str_detect(nectar_flower_work$Population,"^G|^I"), "SI", "SC")
nectar_flower_work$Population <- droplevels(nectar_flower_work$Population)

scent_nectar_work <- scent_nectar %>% drop_na(total_tol) %>%  group_by(Population) %>% filter(length(unique(Plant_id))>=8)

scent_nectar_work$Population <- recode(scent_nectar_work$Population, `Fr3/IT11`="Fr3", `Fr4/IT12`="Fr4")
scent_nectar_work$Mating_system <- if_else(str_detect(scent_nectar_work$Population,"^G|^I"), "SI", "SC")
scent_nectar_work$Mating_system<-factor(scent_nectar_work$Mating_system, levels=c("SI", "SC"))

comps_nectar_work <- comps_nectar  %>% drop_na(Toluene_adj.x)  %>% group_by(Population) %>% filter(length(unique(Plant_id))>=8)
comps_nectar_work$Population <- recode(comps_nectar_work$Population, `Fr3/IT11`="Fr3", `Fr4/IT12`="Fr4")
comps_nectar_work$Mating_system <- if_else(str_detect(comps_nectar_work$Population,"^G|^I"), "SI", "SC")
comps_nectar_work$Mating_system<-factor(comps_nectar_work$Mating_system, levels=c("SI", "SC"))


nectar_flower_z <- nectar_flower_work %>% filter(nectar_μl==0) %>%  group_by(Population, plant_id) %>% summarize(N_fl=length(flower_id))
                                                                                                                 
                                                                                                                 
```

Dataset manipulation to build plot A:
```{r}
nectar_flower_work$y1 = ((nectar_flower_work$nectar_μl>0)*1)


#need the object: nectar_plotting_zeros

nectar_flower_plotting_zeros <- nectar_flower_work %>% group_by(Population) %>% mutate(nect_mean=mean(y1), nect_min=min(y1), nect_max=max(y1), size_mean=mean(log(Corola_area_mm2)), size_min=min(log(Corola_area_mm2)), size_max=max(log(Corola_area_mm2)), size_se=std.error(log(Corola_area_mm2)), nect_se=std.error(y1)) %>% summarize(nect_mean=unique(nect_mean),nect_min=unique(nect_min), nect_max=unique(nect_max), size_mean=unique(size_mean), size_min=unique(size_min), size_max=unique(size_max), size_se=unique(size_se), nect_se=unique(nect_se)) %>% mutate(Mating_system=if_else(str_detect(Population,"^G|^I"), "SI", "SC"))


```

Making Plot A (logistic regression)
```{r}
panelA <-ggplot(aes(x=size_mean, y=nect_mean,label=Population, color=Mating_system), data=nectar_flower_plotting_zeros)+geom_errorbar(aes(x=size_mean, ymin=nect_mean-nect_se, ymax=nect_mean+nect_se), data=nectar_flower_plotting_zeros, size=1.25, show.legend=F)+geom_errorbarh(aes(y=nect_mean, xmin=size_mean-size_se, xmax=size_mean+size_se), data=nectar_flower_plotting_zeros, size=1.25, show.legend=F)+ geom_smooth(aes(x=log(Corola_area_mm2), y=y1), data=nectar_flower_work, method="glm", method.args = list(family = "binomial"), se=FALSE, color="black", linetype=2)+geom_point(aes(x=log(Corola_area_mm2), y=y1, color=Mating_system), data=nectar_flower_work, show.legend=F)+geom_label_repel(aes(x=size_mean, y=nect_mean,label=Population, color=Mating_system), data=nectar_flower_plotting_zeros, max.overlaps=100,min.segment.length = 0, show.legend=F)+theme_classic(base_size = 16)+xlab(expression(paste("Corolla area, log(", mm^2 ,")")))+ylab("Presence of nectar")+scale_color_viridis(discrete=TRUE,option="magma",begin=.6, end=0.8)
```

Dataset manipulation to build plot B:
```{r}
#in order to get Sig in nectar_flower_plotting, need to run tests on the model

nectar_flower_work$y2 = nectar_flower_work$nectar_μl
nectar_flower_work$y2[which(nectar_flower_work$nectar_μl==0)] = NA

nectar_flower_plotting <- nectar_flower_work %>% filter(nectar_μl>0) %>%  group_by(Population) %>% mutate(nect_mean=mean(log(nectar_μl)), nect_min=min(log(nectar_μl)), nect_max=max(log(nectar_μl)), size_mean=mean(log(Corola_area_mm2)), size_min=min(log(Corola_area_mm2)), size_max=max(log(Corola_area_mm2)), size_se=std.error(log(Corola_area_mm2)), nect_se=std.error(log(nectar_μl))) %>% summarize(nect_mean=unique(nect_mean),nect_min=unique(nect_min), nect_max=unique(nect_max), size_mean=unique(size_mean), size_min=unique(size_min), size_max=unique(size_max), size_se=unique(size_se), nect_se=unique(nect_se)) %>% mutate(Mating_system=if_else(str_detect(Population,"^G|^I"), "SI", "SC"))

size_list <- nectar_flower_plotting %>% arrange(., size_mean) 
size_list$Population <- factor(size_list$Population, levels=c(size_list$Population))

#this is how you change the levels of something without reassigning the values erroneously
nectar_flower_work$Population <- factor(nectar_flower_work$Population, levels=c(size_list$Population))
nectar_flower_plotting$Population <- factor(nectar_flower_plotting$Population, levels=c(size_list$Population))


m2 = lmer(log(y2)~log(Corola_area_mm2)*Population+(1|Population/Plant_ID),data=nectar_flower_work,  na=na.exclude)

plist <- test(emtrends(m2, "Population", var="log(Corola_area_mm2)")) %>% mutate(Sig = if_else(p.value < 0.059, "A", "No"))

#need nectar_flower_plotting object updated with sig

nectar_flower_plotting <- left_join(nectar_flower_plotting, plist, by="Population")







#need nectar_flower_noz

nectar_flower_noz <- nectar_flower_work %>% filter(nectar_μl > 0)
```


Making plot B (population level regression of non-zero nectar values)

```{r}
panelB <- ggplot(aes(x=size_mean, y=nect_mean,label=Population, color=Mating_system), data=nectar_flower_plotting)+geom_errorbar(aes(x=size_mean, ymin=nect_mean-nect_se, ymax=nect_mean+nect_se, alpha=Sig.y), data=nectar_flower_plotting, size=1.25, show.legend=F)+geom_errorbarh(aes(y=nect_mean, xmin=size_mean-size_se, xmax=size_mean+size_se, alpha=Sig.y), data=nectar_flower_plotting, size=1.25, show.legend=F)+geom_smooth(aes(x=log(Corola_area_mm2), y=log(nectar_μl)), data=nectar_flower_noz, method="lm", se=FALSE, color="black", linetype=2)+geom_label_repel(aes(x=size_mean, y=nect_mean,label=Population, color=Mating_system), data=nectar_flower_plotting, max.overlaps=100,min.segment.length = 0, show.legend=F)+theme_classic(base_size = 16)+xlab(expression(paste("Corolla area, log(", mm^2 ,")"))) + ylab(expression(paste("Nectar volume, log(", mu,"l)")))+scale_alpha_manual(values=c(1,0.5), labels=c("1", "0.5"))+scale_color_viridis(discrete=TRUE,option="magma",begin=.6, end=0.8)
```
What do we need to add to get plot C:
```{r}
nectar_flower_work$pred <- fitted(m2)

cors <- nectar_flower_work %>% filter(pred!="NA") %>% group_by(Population) %>% summarize(COR_raw=cor(log(y2),log(Corola_area_mm2)), COR_pred=cor(pred,log(Corola_area_mm2)))

peas <- test(emtrends(m2, "Population", var="log(Corola_area_mm2)")) %>% mutate(COR_raw=cors$COR_raw, COR_pred=cors$COR_pred) %>% mutate(Type=case_when(p.value <0.05~"A",                                                                                              (p.value >0.05 & COR_raw > 0.2) ~ "B",
                                                    (p.value >0.05 & COR_raw < 0.2) ~ "C")) 

test_join <- left_join(nectar_flower_work, peas, by="Population") %>% filter(Type!="C")

#lines <- nectar_flower_work
#lines$Population <- droplevels(lines$Population)
#levels(lines$Population) <- levels(size_list$Population)
#lines <- lines %>% filter(Population %in% peas$Population)
```


Making plot C and let's see how it looks this way:

```{r}
panelC <- ggplot(aes(x=log(Corola_area_mm2), y=pred, color=Mating_system, group=Population), data=nectar_flower_work)+geom_point(aes(x=log(Corola_area_mm2), y=pred, color=Mating_system, group=Population), data=nectar_flower_work)+ facet_wrap(~Population, dir="v")+geom_text(
  data    = nectar_flower_work,
  mapping = aes(x = 3, y = Inf, label = Population),
  hjust="left",
  vjust   = 1)+
    theme_classic(base_size=16)+
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size=1)+
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size=1)+
xlab(expression(paste("Corolla area, log(", mm^2 ,")"))) + ylab(expression(paste("Nectar volume, log(", mu,"l)")))+ theme(legend.position = "none") + 
theme(strip.background = element_blank(),
  strip.text.x = element_blank())+scale_color_viridis(discrete=TRUE,option="magma",begin=.6, end=0.8)+scale_x_continuous(breaks=c(3,4,5))+
geom_smooth(aes(linetype=Type),data=test_join,  method="lm",color="black", se=F)
```
Multi panel
```{r}
ggdraw() +
  draw_plot(panelA, x=0, y=0.6, width=0.5, height=0.4)+
  draw_plot(panelB, x=0.5, y=0.6, width=0.5, height=0.4) +
  draw_plot(panelC, x=0, y=0, width=1, height=0.6)
```

