---
title: "reduced rank regression"
output: html_document
date: '2022-09-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lme4)
library(nlme)
library(lmerTest)
library(knitr)
library(lmerTest)
library(emmeans)
library(ggpubr)
library(plotrix)
library(varTestnlme)
library(reshape2)

library(Hmsc)
library(abind)
library(mgcv)
library(knitr)
```



```{r,eval=FALSE}
scent <- read_csv("honest_signals/scents_honest.csv") %>% mutate(ID=as.character(ID)) 
scent_comps <- read_csv("compounds_honest.csv") %>% mutate(ID=as.character(ID))

nectar_plant <- read_xlsx("honest_signals/nectar_for_scent_HT_short.xlsx") %>% mutate(Plant_id=as.factor(as.character(Plant_id)))

funfun <- function(col, tol.area, N.fl){
  (col/tol.area)*23.6*55*(1/3)*(1/N.fl)
}

scent_comps_calc <- scent_comps %>% mutate_at(c(4:12), ~replace(., is.na(.), 0)) %>% left_join(., scent, by="ID")
scent_comps_calc <-scent_comps_calc  %>% mutate_at(c(4:12), list(~funfun(., Toluene_adj.y,NFlowers.x)))

comps_nectar <- left_join(nectar_plant, scent_comps_calc, by=c("Scent_ID" = "ID"))

comps_nectar_work <- comps_nectar  %>% drop_na(Toluene_adj.x)  %>% group_by(Population) %>% filter(length(unique(Plant_id))>=8)
comps_nectar_work$Population <- recode(comps_nectar_work$Population, `Fr3/IT11`="Fr3", `Fr4/IT12`="Fr4")
comps_nectar_work$Mating_system <- if_else(str_detect(comps_nectar_work$Population,"^G|^I"), "SI", "SC")
comps_nectar_work$Mating_system<-factor(comps_nectar_work$Mating_system, levels=c("SI", "SC"))

nectar_plant <- read_xlsx("honest_signals/nectar_for_scent_HT_short.xlsx") %>% mutate(Plant_id=as.factor(as.character(Plant_id)))

nectar_size_plant <- nectar_flower %>% filter(Corola_area_mm2!="NA") %>%   group_by(Population, plant_id) %>% summarize(size=mean(Corola_area_mm2), nect=mean(nectar_μl)) %>% mutate(Plant_id=as.factor(as.character(plant_id)))

nectar_size_plant <- left_join(nectar_size_plant, nectar_plant,   by=c("Population", "Plant_id")) 



nectar_size_scent <- left_join(comps_nectar_work, nectar_size_plant,  by="Scent_ID") %>%  filter(Scent_ID!="NA") %>% filter(size!="NA")

a <- ggplot(aes(x=Phenylacetaldehyde, y=Mean_nectar), data=comps_nectar_work)+geom_point()+facet_wrap(~Population)+ggtitle("Phenylacetaldehyde")+xlab("")+ylab(expression(paste("Nectar volume, ", mu,"l")))+theme_classic(base_size = 16)

b <- ggplot(aes(x=`Benzyl Alcohol`, y=Mean_nectar), data=comps_nectar_work)+geom_point()+facet_wrap(~Population)+ylab(expression(paste("Nectar volume, ", mu,"l")))+theme_classic(base_size = 16)+ggtitle("Benzyl Alcohol")+xlab(expression(paste("Emission rate (ng ", h^-1, flower^-1, ")")))
ggarrange(a, b, ncol=1, nrow=2)
```

```{r, eval=FALSE}
indat <- nectar_size_scent

Y <- cbind(indat$Mean_nectar.x)

XData = indat[,c(25,29)]
#XData = data.frame(scale(indat$total_tol), scale(indat$size))
#colnames(XData) <- c("total_tol", "size")

#XData = indat[,29]


head(XData)
cor(XData)

XRRRData = indat[,10:18] #volatiles
names(XRRRData) <- c("Benzaldehyde" ,"Acetophenone" ,"BenzylBenzoate"   ,    "Phenylacetaldehyde"   , "BenzylAlcohol" ,      
"PhenylethylAlcohol" ,  "BenzylAcetate"    ,    "FourMethoxybenzaldehyde" ,"FourOxoisophorone"    )

XRRRData = XRRRData[,which(colSums(XRRRData)>0)]
 
head(XRRRData)

XFormula = as.formula(paste("~", paste0(colnames(XData), collapse=" + ")))
XFormula

XRRRFormula = as.formula(paste("~", " -1 + ", paste0(colnames(XRRRData), collapse=" + ")))
XRRRFormula

XRRRDataScaled = data.frame(scale(XRRRData))
dim(XRRRData)

```

```{r, eval=FALSE}
m = Hmsc(Y = as.matrix(Y/mean(Y)), XData=XData, XFormula=XFormula,
         distr="normal", 
         XRRRData=XRRRDataScaled, XRRRFormula=XRRRFormula, ncRRR=1, XRRRScale = TRUE)
#could use scale(y) as response


XData2 = data.frame(XData, XRRRData)
XFormula2 = as.formula(paste("~", paste0(colnames(XData2), collapse=" + ")))
XFormula2

m2 = Hmsc(Y = as.matrix(Y/mean(Y)), XData=XData2, XFormula=XFormula2,
          distr="normal")
```

```{r, eval=FALSE}
#Set sampling parameters
samples = 1000
thin = 100
transient = .5*(thin*samples)
adaptNf = 0.4*(thin*samples)
nChains = 1

a1 = Sys.time()
m = sampleMcmc(m, samples = samples, thin = thin, adaptNf=rep(adaptNf, m$nr), 
               transient = transient, nChains = nChains)
m2 = sampleMcmc(m2, samples = samples, thin = thin, adaptNf=rep(adaptNf, m$nr), 
                transient = transient, nChains = nChains)
b1 = Sys.time()
b1-a1

save(m, file="RRR1mod2809_thin100.RData")
save(m2, file="RRR1mod22809_thin100.RData")
```

```{r}
load(file="RRR1mod2809_thin100.RData")
load(file="RRR1mod22809_thin100.RData")

#parameter estimates, support values, 0.5 is no support, close to zero is support for a negative, close to one is support for positive, some support for scent, can see if it changes with scaling
getPostEstimate(m, "Beta")

post = convertToCodaObject(m)
str(post$Beta[[1]])
plot(post$Beta[,3])

bind0 = function(...) {abind(..., along = 0)}
postList = poolMcmcChains(m$postList, chainIndex = 1:length(m$postList), 
                          start = 1, thin = 1)
valList = lapply(postList, function(a) a[["wRRR"]])
wRRR_post = do.call(bind0, valList)

dim(wRRR_post)
```

```{r}

#posteriors for all of the weights, how the different compounds load onto the trait
par(mfrow=c(3,3))
for(i in 1:9){
  plot(wRRR_post[,1,i], type="l")
}

predY = computePredictedValues(m)
predYm = apply(simplify2array(predY), 1:2, mean)
MF = evaluateModelFit(m, predY)

predY2 = computePredictedValues(m2)
predYm2 = apply(simplify2array(predY2), 1:2, mean)
MF2 = evaluateModelFit(m2, predY2)

MF #for RRR model
MF2
```

```{r}
partition = createPartition(m, nfolds=5)

predY_CV = computePredictedValues(m, partition)
predYm_CV = apply(simplify2array(predY_CV), 1:2, mean)
MF_CV = evaluateModelFit(m, predY_CV)
save(MF_CV, file="MF_CVv2.RData")

predY_CV2 = computePredictedValues(m2, partition)
predYm_CV2 = apply(simplify2array(predY_CV2), 1:2, mean)
MF_CV2 = evaluateModelFit(m2, predY_CV2)
save(MF_CV2, file="MF_CV2v2.RData")

load(file="MF_CV2v2.RData")
load(file="MF_CVv2.RData")
MF_CV #cross validated Rsq, should be and is better for RRR, consistent with RRR representing the structure of the data
MF_CV2
```

```{r}
#getting standardized parameter estimates, can omit if scaling from the start
nX = ncol(m$XData)

post = convertToCodaObject(m)
beta_raw_post = post$Beta[,2:(nX+1)][[1]] #posterior for betas
head(beta_raw_post)

beta_var_post = matrix(NA, nrow=nrow(beta_raw_post), ncol=nX)

XData1 <- as.data.frame(XData)
for(i in 1:nX){
  beta_var_post[,i] = beta_raw_post[,i]*sd(XData1[,i])
}

beta_mean_post = matrix(NA, nrow=nrow(beta_raw_post), ncol=nX)
for(i in 1:nX){
  beta_mean_post[,i] = beta_raw_post[,i]*mean(XData1[,i])
}

beta_raw = apply(beta_raw_post, 2, mean)
beta_raw_lower = apply(beta_raw_post, 2, quantile, c(0.025))
beta_raw_upper = apply(beta_raw_post, 2, quantile, c(0.975))

beta_var = apply(beta_var_post, 2, mean)
beta_var_lower = apply(beta_var_post, 2, quantile, c(0.025))
beta_var_upper = apply(beta_var_post, 2, quantile, c(0.975))

beta_mean = apply(beta_mean_post, 2, mean)
beta_mean_lower = apply(beta_mean_post, 2, quantile, c(0.025))
beta_mean_upper = apply(beta_mean_post, 2, quantile, c(0.975))

resmat_RRR = data.frame(beta_raw = round(beta_raw, 3),
                        L = round(beta_raw_lower, 3),
                        U = round(beta_raw_upper, 3),
                        beta_var = round(beta_var, 3),
                        L = round(beta_var_lower, 3),
                        U = round(beta_var_upper, 3),
                        beta_mean = round(beta_mean*100, 3),
                        L = round(beta_mean_lower, 3),
                        U = round(beta_mean_upper, 3))
```

```{r}
betaRRR = post$Beta[,(nX+2):(m$ncRRR+(nX+1))][[1]] #posterior for beta_RRR
length(betaRRR)
dim(m$XRRR)

comp1_post = matrix(NA, nrow=length(betaRRR), ncol=m$ny)
for(i in 1:length(betaRRR)){
  comp1_post[i,]=m$XRRR %*% as.matrix((wRRR_post[i,1,]))
}

beta_comp1_post=NULL
for(i in 1:1000){
  beta_comp1_post[i]=betaRRR[i]*sd(comp1_post[i,])
}

resmat_RRR[nrow(resmat_RRR)+1,]=c("NA","NA","NA", 
                                  round(mean(beta_comp1_post), 3),
                                  round(quantile(beta_comp1_post, c(0.025)), 3),
                                  round(quantile(beta_comp1_post, c(0.975)), 3),
                                  "NA","NA","NA")
kable(resmat_RRR)
```

```{r}
#for combining results with other studies
bdf = as.numeric(c(resmat_RRR[7, 4:6]))
bdf = bdf*(-1) #Because of  negative beta
bdf[2:3] = bdf[3:2]
bdf = t(as.data.frame(bdf))

save(bdf, file="bdf_pens.RData")

#calculating the corresponding slopes for the original variables

betapost = post$Beta[,(nX+2):(m$ncRRR+(nX+1))][[1]] #posterior for beta_RRR
head(betapost)

beta_raw_post = matrix(NA, nrow=length(betapost), ncol=m$ncORRR)
for(i in 1:length(betapost)){
  beta_raw_post[i,] = t(as.matrix(wRRR_post[i,,])) * betapost[i] #Need matrix * for more than one RRR
}

beta_var_post = matrix(NA, nrow=length(betapost), ncol=m$ncORRR)
for(i in 1:m$ncORRR){
  beta_var_post[,i] = beta_raw_post[,i]*sd(m$XRRRData[,i])
}

XRRRData1 <- as.data.frame(XRRRData)

beta_mean_post = matrix(NA, nrow=length(betapost), ncol=m$ncORRR)
for(i in 1:m$ncORRR){
  beta_mean_post[,i] = beta_raw_post[,i]*(mean(XRRRData1[,i])/sd(XRRRData1[,i]))
}

beta_raw = apply(beta_raw_post, 2, mean)
beta_raw_lower = apply(beta_raw_post, 2, quantile, c(0.025))
beta_raw_upper = apply(beta_raw_post, 2, quantile, c(0.975))

beta_var = apply(beta_var_post, 2, mean)
beta_var_lower = apply(beta_var_post, 2, quantile, c(0.025))
beta_var_upper = apply(beta_var_post, 2, quantile, c(0.975))

beta_mean = apply(beta_mean_post, 2, mean)
beta_mean_lower = apply(beta_mean_post, 2, quantile, c(0.025))
beta_mean_upper = apply(beta_mean_post, 2, quantile, c(0.975))

betamat_RRR = data.frame(beta_raw = round(beta_raw, 3),
                         lower = round(beta_raw_lower, 3),
                         upper = round(beta_raw_upper, 3),
                         beta_var = round(beta_var, 3),
                         beta_mean = round(beta_mean*100, 3),
                         L = round(beta_mean_lower*100, 3),
                         U = round(beta_mean_upper*100, 3))
rownames(betamat_RRR) = colnames(m$XRRRData)

```

```{r}
post = convertToCodaObject(m2)

beta_raw_post = post$Beta[,4:12][[1]] #posterior for betas

beta_var_post = matrix(NA, nrow=nrow(beta_raw_post), ncol=ncol(beta_raw_post))
for(i in 1:ncol(beta_raw_post)){
  beta_var_post[,i] = beta_raw_post[,i]*sd(XData2[,i+2])
}

beta_mean_post = matrix(NA, nrow=nrow(beta_raw_post), ncol=ncol(beta_raw_post))
for(i in 1:ncol(beta_raw_post)){
  beta_mean_post[,i] = beta_raw_post[,i]*mean(XData2[,i+2])
}

beta_raw = apply(beta_raw_post, 2, mean)
beta_raw_lower = apply(beta_raw_post, 2, quantile, c(0.025))
beta_raw_upper = apply(beta_raw_post, 2, quantile, c(0.975))

beta_var = apply(beta_var_post, 2, mean)
beta_var_lower = apply(beta_var_post, 2, quantile, c(0.025))
beta_var_upper = apply(beta_var_post, 2, quantile, c(0.975))

beta_mean = apply(beta_mean_post, 2, mean)
beta_mean_lower = apply(beta_mean_post, 2, quantile, c(0.025))
beta_mean_upper = apply(beta_mean_post, 2, quantile, c(0.975))

resmat_MR = data.frame(beta_raw = round(beta_raw, 3),
                       L = round(beta_raw_lower, 3),
                       U = round(beta_raw_upper, 3),
                       beta_var = round(beta_var, 3),
                       L = round(beta_var_lower, 3),
                       U = round(beta_var_upper, 3),
                       beta_mean = round(beta_mean*100, 3),
                       L = round(beta_mean_lower, 3),
                       U = round(beta_mean_upper, 3))

#results are qualitatively similar between RRR and independent traits
cor(resmat_MR$beta_mean, betamat_RRR$beta_mean)
```

```{r}
mfvals = c(studies="Arabis", apply(data.frame(100*MF$R2, 100*MF2$R2, 100*MF_CV$R2, 100*MF_CV2$R2), 2, round, 1))
mfvals[6] = cor(resmat_MR$beta_mean, betamat_RRR$beta_mean)
save(mfvals, file="mf_pens.RData")

wRRR = getPostEstimate(m, "wRRR")
rrr = as.matrix(m$XRRRData) %*% t(as.matrix(wRRR$mean))

gamdat = data.frame(W=m$Y[,1], r1=rrr[,1], m$XData)
head(gamdat)

gm = gam(W ~ r1 + total_tol + size, family=gaussian, data=gamdat)
#gm = gam(W ~ s(r1) + flwsize + pigment + FlwDate + display + height + flowers, family=gaussian, data=gamdat)
summary(gm)


par(mfrow=c(2,2))
par(mar=c(4,4,2,2))
res = vis.gam(gm, c("size","r1"), plot.type="contour", type="response",
              xlab="Flower size",
              ylab="Scent selection axis 1",
              main="", color="bw")

points(gamdat$size, gamdat$r1, col="grey", pch=16, cex=1*gamdat$W)

par(mar=c(4,6,2,2), xpd=T)
out = barplot(sort(betamat_RRR$beta_mean, dec=F), xlim=c(-1,1), col="royalblue",
              xlab="Mean-scaled selection gradient (%)", las=1, horiz=T)
text(y=out, par("usr")[3] + -1, srt = 0, adj = 0,cex=.7,
     labels = gsub("X","",colnames(XRRRData)[order(betamat_RRR$beta_mean, decreasing=F)]), xpd = TRUE)

```

